(()=>{'use strict';
const K={records:'kk_records',goal:'kk_goal',memo:'kk_memo',wishes:'kk_wishes',seed:'kk_seed'};
const $=s=>document.querySelector(s),content=$('#content'),overlay=$('#overlay');let page='home',calDate=new Date(),editId=null;
const today=()=>new Date().toISOString().slice(0,10),read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
if(!localStorage.getItem(K.seed)){const d=today().slice(0,7);write(K.records,[{id:'demo-income',type:'income',amount:250000,date:d+'-01',memo:'今月の収入',createdAt:new Date().toISOString()},{id:'demo-expense',type:'expense',amount:187650,date:d+'-02',memo:'今月の支出',createdAt:new Date().toISOString()}]);write(K.goal,100000);write(K.seed,true)}
const yen=n=>'￥'+Math.abs(Math.round(n)).toLocaleString('ja-JP'),records=()=>read(K.records,[]),monthKey=()=>new Date().toISOString().slice(0,7);
const totals=(m=monthKey())=>records().filter(r=>r.date.startsWith(m)).reduce((a,r)=>(a[r.type]+=Number(r.amount),a),{income:0,expense:0});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function nav(){const items=[['home','🏠','ホーム'],['records','📖','きろく'],['savings','🐷','ちょきん'],['wishes','⭐','ほしいもの'],['settings','•••','その他']];$('#bottomNav').innerHTML=items.map(x=>`<button class="nav-btn ${page===x[0]?'active':''}" data-page="${x[0]}" aria-label="${x[2]}"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('')}
function route(p){content.classList.add('swap');setTimeout(()=>{page=p;render();content.scrollTop=0;content.classList.remove('swap')},180)}
function render(){content.dataset.page=page;nav();const navArt=document.createElement('img');navArt.className='nav-reference-art';navArt.src='./assets/ui/reference-controls.jpg';navArt.alt='';navArt.setAttribute('aria-hidden','true');$('#bottomNav').prepend(navArt);({home,records:recordList,savings,wishes,settings,input,graph,calendar,memo}[page]||home)();if(page==='home'){const savingArt=document.createElement('img');savingArt.className='saving-reference-art';savingArt.src='./assets/ui/reference-controls.jpg';savingArt.alt='';savingArt.setAttribute('aria-hidden','true');$('.save-card').prepend(savingArt);const featureArt=document.createElement('img');featureArt.className='feature-reference-art';featureArt.src='./assets/ui/reference-controls.jpg';featureArt.alt='';featureArt.setAttribute('aria-hidden','true');$('.features').prepend(featureArt)}}
function home(){const t=totals(),bal=t.income-t.expense,g=read(K.goal,100000),pct=g?Math.round(bal/g*100):0,remain=g-bal;content.innerHTML=`<section class="rpg summary"><div class="money-row income"><b>💰 収入</b><i class="dots"></i><span class="amount">${yen(t.income)}</span></div><div class="money-row expense"><b>👛 支出</b><i class="dots"></i><span class="amount">${yen(t.expense)}</span></div><div class="money-row ${bal<0?'expense':'balance'}"><b>🪙 残り</b><i class="dots"></i><span class="amount">${bal<0?'-':''}${yen(bal)}</span></div></section><section class="save-card"><div class="save-title">🐷 今月の貯金 ✦</div><div class="save-grid"><div class="save-numbers">🚩 目標貯金額<strong>${yen(g)}</strong>⭐ 今月の貯金額<strong>${bal<0?'-':''}${yen(bal)}</strong></div><div class="progress-wrap"><b>あと ${remain>0?yen(remain):'達成！'}</b><div class="progress"><span style="width:${Math.max(0,Math.min(100,pct))}%"></span></div><strong>${pct}%</strong></div></div></section><div class="features"><button class="feature" data-page="input"><span class="big">✏️</span>かんたん入力<small>収入・支出を記録する</small></button><button class="feature" data-page="graph"><span class="big">📊</span>グラフ<small>収支のグラフを確認する</small></button><button class="feature" data-page="calendar"><span class="big">📅</span>カレンダー<small>カレンダーで振り返る</small></button><button class="feature" data-page="memo"><span class="big">🐷</span>貯金メモ<small>目標やメモを書き留める</small></button></div>`}
function input(){const r=editId?records().find(x=>x.id===editId):null;content.innerHTML=`<section class="rpg window"><h2>${r?'記録を編集':'✏️ かんたん入力'}</h2><form id="recordForm" class="form-grid"><div class="type-switch"><button type="button" data-type="income" class="${!r||r.type==='income'?'active':''}">収入</button><button type="button" data-type="expense" class="${r?.type==='expense'?'active':''}">支出</button></div><input type="hidden" name="type" value="${r?.type||'income'}"><label>金額<input name="amount" type="number" inputmode="numeric" min="1" max="999999999" required value="${r?.amount||''}"></label><label>日付<input name="date" type="date" required value="${r?.date||today()}"></label><label>メモ<input name="memo" maxlength="80" value="${esc(r?.memo||'')}"></label><button class="app-btn" type="submit">保存する</button></form></section>`}
function recordList(){const rs=[...records()].sort((a,b)=>b.date.localeCompare(a.date));content.innerHTML=`<section class="rpg window"><h2>📖 収入・支出履歴</h2>${rs.length?rs.map(r=>`<article class="record"><div><b class="${r.type}">${r.date}　${r.type==='income'?'収入':'支出'}</b><br>${esc(r.memo)||'（メモなし）'}</div><div><b>${yen(r.amount)}</b><div class="record-actions"><button class="app-btn mini" data-edit="${r.id}">編集</button><button class="app-btn mini" data-del="${r.id}">削除</button></div></div></article>`).join(''):'<p class="empty">記録はまだありません</p>'}</section>`}
function savings(){const g=read(K.goal,100000),t=totals(),b=t.income-t.expense,p=g?Math.round(b/g*100):0;const months=[...new Set(records().map(r=>r.date.slice(0,7)))].sort().reverse();content.innerHTML=`<section class="rpg window"><h2>🐷 ちょきん</h2><p>今月の貯金額 <b>${b<0?'-':''}${yen(b)}</b></p><p>達成率 <b>${p}%</b> ／ 残り <b>${yen(Math.max(0,g-b))}</b></p><div class="progress"><span style="width:${Math.max(0,Math.min(100,p))}%"></span></div><form id="goalForm" class="form-grid"><label>目標貯金額<input name="goal" type="number" inputmode="numeric" min="1" max="999999999" value="${g}" required></label><button class="app-btn">目標を変更</button></form><h2>月ごとの貯金</h2>${months.map(m=>{const x=totals(m);return`<div class="record"><span>${m}</span><b>${yen(x.income-x.expense)}</b></div>`}).join('')}</section>`}
function graph(){const t=totals(),vals=[t.income,t.expense,t.income-t.expense],mx=Math.max(1,...vals.map(Math.abs));content.innerHTML=`<section class="rpg window"><h2>📊 今月のグラフ</h2><div class="chart">${vals.map((v,i)=>`<div class="bar ${['income','expense','balance'][i]}" style="height:${Math.max(6,Math.abs(v)/mx*85)}%"><span>${yen(v)}</span>${['収入','支出','残り'][i]}</div>`).join('')}</div></section>`}
function calendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),key=`${y}-${String(m+1).padStart(2,'0')}`;let cells='<div>日</div><div>月</div><div>火</div><div>水</div><div>木</div><div>金</div><div>土</div>'+Array(first).fill('<i></i>').join('');for(let d=1;d<=last;d++){const date=`${key}-${String(d).padStart(2,'0')}`,mark=records().some(r=>r.date===date);cells+=`<button class="day ${mark?'mark':''}" data-date="${date}">${d}</button>`}content.innerHTML=`<section class="rpg window"><div class="calendar-head"><button class="app-btn mini" data-cal="-1">◀ 前月</button><h2>${y}年${m+1}月</h2><button class="app-btn mini" data-cal="1">次月 ▶</button></div><div class="calendar">${cells}</div><div id="dayDetail"></div></section>`}
function memo(){content.innerHTML=`<section class="rpg window"><h2>🐷 貯金メモ</h2><label>自由に書き留めてください<textarea id="savingMemo" placeholder="目標や買いたいものなど">${esc(read(K.memo,''))}</textarea></label><p>入力内容は自動保存されます。</p></section>`}
function wishes(){const ws=read(K.wishes,[]);content.innerHTML=`<section class="rpg window"><h2>⭐ ほしいもの</h2><form id="wishForm" class="form-grid"><input name="id" type="hidden"><label>名前<input name="name" required maxlength="40"></label><label>価格<input name="price" type="number" inputmode="numeric" min="1" max="999999999" required></label><label>メモ<input name="memo" maxlength="80"></label><button class="app-btn">追加する</button></form><p class="wish-total">合計 ${yen(ws.reduce((a,w)=>a+Number(w.price),0))}</p>${ws.map(w=>`<article class="record"><div><b>${esc(w.name)}</b><br>${esc(w.memo)}</div><div><b>${yen(w.price)}</b><div><button class="app-btn mini" data-wedit="${w.id}">編集</button><button class="app-btn mini" data-wdel="${w.id}">削除</button></div></div></article>`).join('')}</section>`}
function settings(){content.innerHTML=`<section class="rpg window"><h2>••• その他・設定</h2><h3>データについて</h3><p>記録はこの端末のブラウザ内（localStorage）だけに保存され、外部へ送信されません。</p><button class="app-btn" id="clearAll">データを全削除</button><h3>アプリ情報</h3><p>かんたん かけいぼ v1.0<br>最終更新日：2026年8月9日<br>最終更新時間：00:48:14<br>オフライン対応の静的Webアプリです。</p></section>`}
function modal(html){overlay.innerHTML=`<section class="rpg modal">${html}</section>`;overlay.hidden=false}function closeModal(){overlay.hidden=true;overlay.innerHTML=''}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]')?.dataset.page;if(p)return route(p);const ty=e.target.closest('[data-type]')?.dataset.type;if(ty){$('[name=type]').value=ty;document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===ty))}const ed=e.target.closest('[data-edit]')?.dataset.edit;if(ed){editId=ed;route('input')}const del=e.target.closest('[data-del]')?.dataset.del;if(del&&confirm('この記録を消しますか？')){write(K.records,records().filter(r=>r.id!==del));render();toast('記録を消しました')}const c=e.target.closest('[data-cal]')?.dataset.cal;if(c){calDate=new Date(calDate.getFullYear(),calDate.getMonth()+Number(c),1);calendar()}const dt=e.target.closest('[data-date]')?.dataset.date;if(dt){const rs=records().filter(r=>r.date===dt);$('#dayDetail').innerHTML=`<h3>${dt}</h3>${rs.length?rs.map(r=>`<p>${r.type==='income'?'収入':'支出'} ${yen(r.amount)} ${esc(r.memo)}</p>`).join(''):'<p>記録なし</p>'}`}const we=e.target.closest('[data-wedit]')?.dataset.wedit;if(we){const w=read(K.wishes,[]).find(x=>x.id===we),f=$('#wishForm');f.id.value=w.id;f.name.value=w.name;f.price.value=w.price;f.memo.value=w.memo;f.querySelector('button').textContent='更新する'}const wd=e.target.closest('[data-wdel]')?.dataset.wdel;if(wd&&confirm('このほしいものを消しますか？')){write(K.wishes,read(K.wishes,[]).filter(w=>w.id!==wd));render()}if(e.target.id==='clearAll')modal('<h2>データを全削除</h2><p>すべての記録・貯金メモ・ほしいものを消しますか？ 元に戻せません。</p><button class="app-btn" id="confirmClear">削除する</button> <button class="app-btn" id="closeModal">やめる</button>');if(e.target.id==='confirmClear'){Object.values(K).forEach(k=>localStorage.removeItem(k));localStorage.setItem(K.seed,'true');closeModal();route('home');toast('すべてのデータを消しました')}if(e.target.id==='closeModal'||e.target===overlay)closeModal()});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(f.id==='recordForm'){const d=Object.fromEntries(new FormData(f)),a=Number(d.amount);if(!Number.isFinite(a)||a<=0||a>999999999)return toast('金額を確認してください');let rs=records(),obj={id:editId||crypto.randomUUID(),type:d.type,amount:a,date:d.date,memo:d.memo.trim(),createdAt:editId?(rs.find(r=>r.id===editId)?.createdAt||new Date().toISOString()):new Date().toISOString()};rs=editId?rs.map(r=>r.id===editId?obj:r):[...rs,obj];write(K.records,rs);editId=null;toast('記録しました');route('home')}if(f.id==='goalForm'){write(K.goal,Number(new FormData(f).get('goal')));toast('目標を変更しました');render()}if(f.id==='wishForm'){const d=Object.fromEntries(new FormData(f)),ws=read(K.wishes,[]),w={id:d.id||crypto.randomUUID(),name:d.name.trim(),price:Number(d.price),memo:d.memo.trim()};write(K.wishes,d.id?ws.map(x=>x.id===d.id?w:x):[...ws,w]);toast(d.id?'更新しました':'追加しました');render()}});
document.addEventListener('input',e=>{if(e.target.id==='savingMemo'){write(K.memo,e.target.value);toast('自動保存しました')}});
document.addEventListener('click',e=>{if(e.target.closest('[data-page]')&&!overlay.hidden)closeModal();const id=e.target.closest('[data-wedit]')?.dataset.wedit;if(!id)return;e.stopImmediatePropagation();const w=read(K.wishes,[]).find(x=>x.id===id),f=$('#wishForm');for(const n of ['id','name','price','memo'])f.querySelector(`[name="${n}"]`).value=w[n];f.querySelector('button').textContent='更新する'},true);
$('#menuBtn').addEventListener('click',()=>modal('<h2>メニュー</h2><div class="menu-list"><button class="app-btn" data-page="input">かんたん入力</button><button class="app-btn" data-page="records">きろく</button><button class="app-btn" data-page="savings">ちょきん</button><button class="app-btn" id="closeModal">とじる</button></div>'));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));render();
})();
